# Generated by Django 3.0.2 on 2020-07-17 12:48

import IKVindustry.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IKVassistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fanr', models.CharField(max_length=200, verbose_name='FA-Nummer')),
                ('company', models.CharField(max_length=200, verbose_name='Firma')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('short_title', models.CharField(max_length=200, verbose_name='Kurztitel')),
                ('kind', models.CharField(choices=[('RD', 'Forschung und Entwicklung'), ('S', 'Dienstleistung')], max_length=200, verbose_name='Art')),
                ('finish_finance_a', models.DateField(null=True, verbose_name='Ende Buchhaltung (Assistent)')),
                ('finish_finance_al', models.DateField(null=True, verbose_name='Ende Buchhaltung (Abteilungsleiter)')),
                ('finish_finance_s', models.DateField(null=True, verbose_name='Ende Buchhaltung (Studenten)')),
                ('added', models.DateField(editable=False, verbose_name='Letzte Änderung')),
                ('status', models.CharField(choices=[('CR', 'angelegt'), ('GO', 'laufend'), ('END', 'beendet'), ('DD', 'tot')], max_length=3, verbose_name='Status')),
                ('sum_wp_instruct', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Summe beauftragter Arbeitspakte')),
                ('sum_wp_invoiced', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Summe fakturierter Arbeitspakte')),
                ('sum_wp', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Summe Arbeitspakte')),
                ('released', models.BooleanField(default=False, verbose_name='Projektgelder freigegeben')),
                ('al_budget', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='AL-Budget')),
                ('al_budget_spent', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Ausgegebenes AL-Budget')),
                ('al_budget_left', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Verbleibendes Assistenten Budget')),
                ('assi_budget', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Assistenten Budget')),
                ('assi_budget_spent', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Ausgegebenes Assistenten Budget')),
                ('assi_budget_left', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Verbleibendes Assistenten Budget')),
                ('students_budget', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Studenten Budget')),
            ],
            options={
                'verbose_name': 'Industrieprojekt',
                'verbose_name_plural': 'Industrieprojekte',
            },
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('material', models.DecimalField(decimal_places=2, default=17.5, max_digits=5, verbose_name='Material [%]')),
                ('staff', models.DecimalField(decimal_places=2, default=17.5, max_digits=5, verbose_name='Personal [%]')),
                ('foreign', models.BooleanField(default=False, verbose_name='Fremdleistung')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Teilschrittvolumen')),
                ('instruct_at', models.DateField(blank=True, null=True, verbose_name='Beauftragt am')),
                ('invoiced_at', models.DateField(blank=True, null=True, verbose_name='Fakturiert am')),
                ('al_budget', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='AL-Budget')),
                ('assi_material_budget', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Assistenten Materialbudget')),
                ('assi_students_budget', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Assistenten Studentenbudget')),
                ('assistant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IKVassistant.Assistant', verbose_name='Bearbeiter')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IKVindustry.Industry', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Teilschritt',
                'verbose_name_plural': 'Teilschritte',
            },
        ),
        migrations.CreateModel(
            name='Outgoings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ausgaben inkl. MwSt:')),
                ('description', models.TextField(max_length=200, verbose_name='Beschreibung')),
                ('added', models.DateField(editable=False, verbose_name='Hinzugefügt')),
                ('kind', models.CharField(choices=[('AL', 'AL-Budget'), ('A', 'Assistenten Budget')], max_length=2, verbose_name='Budget')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IKVindustry.Industry', verbose_name='Projekt')),
            ],
        ),
        migrations.CreateModel(
            name='IndustryFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=IKVindustry.models.industry_path, verbose_name='Datei')),
                ('description', models.CharField(max_length=200, verbose_name='Beschreibung')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IKVindustry.Industry')),
            ],
            options={
                'verbose_name': 'Industrie Datei',
                'verbose_name_plural': 'Industrie Dateien',
            },
        ),
    ]
