# Generated by Django 3.0.2 on 2020-07-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IKVindustry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='status',
            field=models.CharField(choices=[('CR', 'angelegt'), ('GO', 'laufend'), ('END', 'beendet'), ('DD', 'nicht beauftragt')], max_length=3, verbose_name='Status'),
        ),
    ]
