# Generated by Django 3.1.1 on 2020-09-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IKVindustry', '0002_auto_20200730_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='kind',
            field=models.CharField(choices=[('RD', 'F&E'), ('S', 'Routine')], max_length=200, verbose_name='Art'),
        ),
    ]
